### ISSUE TITLE
draft OSTI label

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-doi-service#154]
**Describe the bug**
When one draft the attached osti label an error generated.
% pds-doi-cmd draft -i /tmp/toto.xml -s loubrieu@jpl.nasa.gov -n eng
INFO:pds_doi_service.core.cmd.pds_doi_cmd:run_dir /Users/loubrieu/PycharmProjects/pds-doi-service
INFO:pds_doi_core.actions.actions:input = /tmp/toto.xml
INFO:pds_doi_core.actions.actions:node = eng
INFO:pds_doi_core.actions.actions:submitter = loubrieu@jpl.nasa.gov
INFO:pds_doi_core.actions.actions:lidvid = None
INFO:pds_doi_core.actions.actions:force = False
INFO:pds_doi_core.actions.actions:keywords = 
INFO:pds_doi_service.core.actions.draft:input_file /tmp/toto.xml
DEBUG:pds_doi_service.core.actions.draft:force_flag,input_file (False, '/tmp/toto.xml')
INFO:pds_doi_service.core.input.input_util:Reading local file path /tmp/toto.xml
INFO:pds_doi_service.core.util.doi_validator:xsd_filename,is_valid ('/Users/loubrieu/PycharmProjects/pds-doi-service/pds_doi_service/core/util/iad_schema.xsd', False)
Traceback (most recent call last):
  File "/Users/loubrieu/PycharmProjects/pds-doi-service/pds_doi_service/core/input/input_util.py", line 117, in parse_xml_file
    dois.append(self._label_util.get_doi_fields_from_pds4(xml_tree))
  File "/Users/loubrieu/PycharmProjects/pds-doi-service/pds_doi_service/core/input/pds4_util.py", line 40, in get_doi_fields_from_pds4
    doi_fields = self.process_pds4_fields(pds4_fields)
  File "/Users/loubrieu/PycharmProjects/pds-doi-service/pds_doi_service/core/input/pds4_util.py", line 202, in process_pds4_fields
    product_class = pds4_fields['product_class']
KeyError: 'product_class'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/loubrieu/PycharmProjects/pds-doi-service/pds_doi_service/core/actions/draft.py", line 336, in _run_single_file
    input_file, keywords
  File "/Users/loubrieu/PycharmProjects/pds-doi-service/pds_doi_service/core/actions/draft.py", line 304, in _transform_label_into_osti_record
    o_dois = input_util.parse_dois_from_input_file(input_file)
  File "/Users/loubrieu/PycharmProjects/pds-doi-service/pds_doi_service/core/input/input_util.py", line 373, in parse_dois_from_input_file
    dois = self._read_from_path(input_file)
  File "/Users/loubrieu/PycharmProjects/pds-doi-service/pds_doi_service/core/input/input_util.py", line 277, in _read_from_path
    dois = read_function(path)
  File "/Users/loubrieu/PycharmProjects/pds-doi-service/pds_doi_service/core/input/input_util.py", line 120, in parse_xml_file
    f'Could not parse xml file {xml_path} as either a PDS4 label '
pds_doi_service.core.input.exceptions.InputFormatException: Could not parse xml file /tmp/toto.xml as either a PDS4 label or OSTI output label.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/loubrieu/PycharmProjects/pds-doi-service/venv/bin/pds-doi-cmd", line 11, in <module>
    load_entry_point('pds-doi-service', 'console_scripts', 'pds-doi-cmd')()
  File "/Users/loubrieu/PycharmProjects/pds-doi-service/pds_doi_service/core/cmd/pds_doi_cmd.py", line 39, in main
    output = action.run()
  File "/Users/loubrieu/PycharmProjects/pds-doi-service/pds_doi_service/core/actions/draft.py", line 411, in run
    return self._draft_input_files(self._input)
  File "/Users/loubrieu/PycharmProjects/pds-doi-service/pds_doi_service/core/actions/draft.py", line 222, in _draft_input_files
    self._keywords
  File "/Users/loubrieu/PycharmProjects/pds-doi-service/pds_doi_service/core/actions/draft.py", line 360, in _run_single_file
    raise CriticalDOIException(err)
pds_doi_service.core.input.exceptions.CriticalDOIException: Could not parse xml file /tmp/toto.xml as either a PDS4 label or OSTI output label.

[toto.xml.zip](https://github.com/NASA-PDS/pds-doi-service/files/6025511/toto.xml.zip)

**Comment by tloubrieu-jpl** [comment]
The OSTI format returned by OSTI after submission does not validate the schema as-is. Need to be modified to validate.
